# Code generated by daco; DO NOT EDIT.

import pyspark.sql.types as T

_Attachments = T.StructType([
    T.StructField("file_name", T.StringType(), nullable=False),
    T.StructField("content_type", T.StringType(), nullable=False),
    T.StructField("file_size", T.LongType(), nullable=False),
    T.StructField("file_url", T.StringType(), nullable=True),
])

email_send_schema = T.StructType([
    T.StructField("id", T.StringType(), nullable=False),
    T.StructField("to_email", T.StringType(), nullable=False),
    T.StructField("cc_email", T.ArrayType(T.StringType()), nullable=True),
    T.StructField("bcc_email", T.ArrayType(T.StringType()), nullable=True),
    T.StructField("from_email", T.StringType(), nullable=False),
    T.StructField("subject", T.StringType(), nullable=False),
    T.StructField("body_text", T.StringType(), nullable=True),
    T.StructField("body_html", T.StringType(), nullable=True),
    T.StructField("attachments", T.ArrayType(_Attachments), nullable=True),
    T.StructField("status", T.StringType(), nullable=False),
    T.StructField("provider", T.StringType(), nullable=True),
    T.StructField("provider_message_id", T.StringType(), nullable=True),
    T.StructField("retry_count", T.LongType(), nullable=True),
    T.StructField("error_message", T.StringType(), nullable=True),
    T.StructField("sent_at", T.TimestampType(), nullable=True),
    T.StructField("created_at", T.TimestampType(), nullable=False),
    T.StructField("updated_at", T.TimestampType(), nullable=True),
])
