# Code generated by daco; DO NOT EDIT.

from __future__ import annotations

import dataclasses
from typing import Optional


@dataclasses.dataclass
class Trace:
    _record_id: Optional[str] = None
    _source_table: Optional[str] = None


@dataclasses.dataclass
class UserEventsSchema:
    dt: str
    game_id: int
    game_var_id: int
    trns_tp: int
    acc_id: Optional[str] = None
    year_: Optional[int] = None
    bd_id: Optional[int] = None
    ret_id: Optional[int] = None
    parent_ret_id: Optional[int] = None
    oper_id: Optional[int] = None
    term_id: Optional[str] = None
    empl_id: Optional[str] = None
    external_retailer_id: Optional[int] = None
    played_draw: Optional[int] = None
    product_id: Optional[int] = None
    coupons: Optional[str] = None
    coupons_gm_var: Optional[str] = None
    cols: Optional[str] = None
    gross_amn: Optional[str] = None
    net_amn: Optional[str] = None
    refund_amn: Optional[str] = None
    tax_amn: Optional[str] = None
    bonus_amn: Optional[str] = None
    disc_amn: Optional[str] = None
    comm_amn: Optional[str] = None
    fee_amn: Optional[str] = None
    refund_coupons: Optional[str] = None
    refund_fee_cpns: Optional[str] = None
    _record_id: Optional[str] = None
    _load_date: Optional[str] = None
    _trace: Optional[Trace] = None
    _dq_issue: Optional[bool] = None
    _dq_issue_reason: Optional[list[str]] = None
    _silver_ts: Optional[str] = None
