# Code generated by daco; DO NOT EDIT.

import pyspark.sql.types as T

_Trace = T.StructType([
    T.StructField("_record_id", T.StringType(), nullable=True),
    T.StructField("_source_table", T.StringType(), nullable=True),
])

user_events_schema = T.StructType([
    T.StructField("dt", T.StringType(), nullable=False),
    T.StructField("game_id", T.LongType(), nullable=False),
    T.StructField("game_var_id", T.LongType(), nullable=False),
    T.StructField("trns_tp", T.LongType(), nullable=False),
    T.StructField("acc_id", T.LongType(), nullable=True),
    T.StructField("year_", T.LongType(), nullable=True),
    T.StructField("bd_id", T.LongType(), nullable=True),
    T.StructField("ret_id", T.LongType(), nullable=True),
    T.StructField("parent_ret_id", T.LongType(), nullable=True),
    T.StructField("oper_id", T.LongType(), nullable=True),
    T.StructField("term_id", T.StringType(), nullable=True),
    T.StructField("empl_id", T.StringType(), nullable=True),
    T.StructField("external_retailer_id", T.LongType(), nullable=True),
    T.StructField("played_draw", T.LongType(), nullable=True),
    T.StructField("product_id", T.LongType(), nullable=True),
    T.StructField("coupons", T.StringType(), nullable=True),
    T.StructField("coupons_gm_var", T.StringType(), nullable=True),
    T.StructField("cols", T.StringType(), nullable=True),
    T.StructField("gross_amn", T.StringType(), nullable=True),
    T.StructField("net_amn", T.StringType(), nullable=True),
    T.StructField("refund_amn", T.StringType(), nullable=True),
    T.StructField("tax_amn", T.StringType(), nullable=True),
    T.StructField("bonus_amn", T.StringType(), nullable=True),
    T.StructField("disc_amn", T.StringType(), nullable=True),
    T.StructField("comm_amn", T.StringType(), nullable=True),
    T.StructField("fee_amn", T.StringType(), nullable=True),
    T.StructField("refund_coupons", T.StringType(), nullable=True),
    T.StructField("refund_fee_cpns", T.StringType(), nullable=True),
    T.StructField("_record_id", T.StringType(), nullable=True, metadata={"comment": "Unique identifier for the record."}),
    T.StructField("_load_date", T.StringType(), nullable=True, metadata={"comment": "Timestamp indicating when the record was loaded."}),
    T.StructField("_trace", _Trace, nullable=True, metadata={"comment": "Tracking metadata for lineage and traceability."}),
    T.StructField("_dq_issue", T.BooleanType(), nullable=True, metadata={"comment": "Flag indicating if the record has a data quality issue."}),
    T.StructField("_dq_issue_reason", T.ArrayType(T.StringType()), nullable=True, metadata={"comment": "Reason for the data quality issue."}),
    T.StructField("_silver_ts", T.StringType(), nullable=True, metadata={"comment": "Timestamp indicating when the record was written."}),
])
